// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenImageFilesDialog():Promise<Array<string>>;

export function SaveCSVDialog(arg1:string):Promise<string>;

export function SidecarURL():Promise<string>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
