// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BubbleIsOpen() {
  return window['go']['main']['App']['BubbleIsOpen']();
}

export function BubbleTaskDone() {
  return window['go']['main']['App']['BubbleTaskDone']();
}

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function CloseBubble() {
  return window['go']['main']['App']['CloseBubble']();
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function EnterPickerMode() {
  return window['go']['main']['App']['EnterPickerMode']();
}

export function ExitPickerMode() {
  return window['go']['main']['App']['ExitPickerMode']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetOpenWindows() {
  return window['go']['main']['App']['GetOpenWindows']();
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function OpenBubble() {
  return window['go']['main']['App']['OpenBubble']();
}

export function OpenDownloadPage(arg1) {
  return window['go']['main']['App']['OpenDownloadPage'](arg1);
}

export function OpenImageFilesDialog() {
  return window['go']['main']['App']['OpenImageFilesDialog']();
}

export function OpenInBrowser(arg1, arg2) {
  return window['go']['main']['App']['OpenInBrowser'](arg1, arg2);
}

export function PipClose() {
  return window['go']['main']['App']['PipClose']();
}

export function PipFrame(arg1) {
  return window['go']['main']['App']['PipFrame'](arg1);
}

export function PipOpen(arg1) {
  return window['go']['main']['App']['PipOpen'](arg1);
}

export function PipStatus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PipStatus'](arg1, arg2, arg3, arg4);
}

export function PrepareScreenPick() {
  return window['go']['main']['App']['PrepareScreenPick']();
}

export function SaveCSVDialog(arg1) {
  return window['go']['main']['App']['SaveCSVDialog'](arg1);
}

export function SaveCSVToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveCSVToFile'](arg1, arg2);
}

export function SaveExcelToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExcelToFile'](arg1, arg2);
}

export function SaveTextToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextToFile'](arg1, arg2);
}

export function SetAlwaysOnTop(arg1, arg2) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1, arg2);
}

export function SetBubbleAnimations(arg1) {
  return window['go']['main']['App']['SetBubbleAnimations'](arg1);
}

export function SetBubbleSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetBubbleSource'](arg1, arg2, arg3, arg4);
}

export function SetBubbleStyle(arg1) {
  return window['go']['main']['App']['SetBubbleStyle'](arg1);
}

export function SetBubbleTheme(arg1) {
  return window['go']['main']['App']['SetBubbleTheme'](arg1);
}

export function SetBubbleThemeKey(arg1) {
  return window['go']['main']['App']['SetBubbleThemeKey'](arg1);
}

export function SetHideFromCapture(arg1) {
  return window['go']['main']['App']['SetHideFromCapture'](arg1);
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function SidecarURL() {
  return window['go']['main']['App']['SidecarURL']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
