// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate(arg1:boolean):Promise<main.UpdateInfo>;

export function CloseBubble():Promise<void>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function EnterPickerMode():Promise<void>;

export function ExitPickerMode():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetOpenWindows():Promise<Array<main.WindowInfo>>;

export function InstallUpdate(arg1:string):Promise<void>;

export function OpenBubble():Promise<void>;

export function OpenDownloadPage(arg1:string):Promise<void>;

export function OpenImageFilesDialog():Promise<Array<string>>;

export function PrepareScreenPick():Promise<void>;

export function SaveCSVDialog(arg1:string):Promise<string>;

export function SaveCSVToFile(arg1:string,arg2:string):Promise<string>;

export function SetAlwaysOnTop(arg1:boolean,arg2:boolean):Promise<void>;

export function SidecarURL():Promise<string>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
