// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenImageFilesDialog() {
  return window['go']['main']['App']['OpenImageFilesDialog']();
}

export function SaveCSVDialog(arg1) {
  return window['go']['main']['App']['SaveCSVDialog'](arg1);
}

export function SidecarURL() {
  return window['go']['main']['App']['SidecarURL']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
