// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseBubble() {
  return window['go']['main']['App']['CloseBubble']();
}

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function EnterPickerMode() {
  return window['go']['main']['App']['EnterPickerMode']();
}

export function ExitPickerMode() {
  return window['go']['main']['App']['ExitPickerMode']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetOpenWindows() {
  return window['go']['main']['App']['GetOpenWindows']();
}

export function OpenBubble() {
  return window['go']['main']['App']['OpenBubble']();
}

export function OpenDownloadPage(arg1) {
  return window['go']['main']['App']['OpenDownloadPage'](arg1);
}

export function OpenImageFilesDialog() {
  return window['go']['main']['App']['OpenImageFilesDialog']();
}

export function PrepareScreenPick() {
  return window['go']['main']['App']['PrepareScreenPick']();
}

export function SaveCSVDialog(arg1) {
  return window['go']['main']['App']['SaveCSVDialog'](arg1);
}

export function SaveCSVToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveCSVToFile'](arg1, arg2);
}

export function SetAlwaysOnTop(arg1, arg2) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1, arg2);
}

export function SidecarURL() {
  return window['go']['main']['App']['SidecarURL']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
